networks:
  emotibot:
    external: true
    name: emotibot
services:
  data-science-project:
    container_name: data-science-project
    image: harbor.lishang4.com/lib/data-science-project:ec35816-20220110-1153
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 5125M
    ports:
     - "9234:9234"
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:rw
version: '3.7'
